version: '3'

services:
  app:
    build: ./
    environment:
      REDIS_ADDR: "redis:6379"
      JWT_KEY: CHANGE_ME
    ports:
      - "8080:8080"
    links:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: always
