version: '3'

services:

  postgresql:
    image: 'postgres:latest'
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      - TZ=America/Los_Angeles
      - POSTGRES_DB=mydb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
